# Problem 29 : How many distinct terms are in the sequence generated by a^b for a in 2..100 and b in 2..100

nums = Array.new

for a in 2..100
	for b in 2..100
		nums.push(a**b)
	end
end

puts nums.uniq.length